
"""
System Administration Utility
Legitimate tool for system management
"""
import base64

# Admin functions (encoded to prevent casual modification)
ADMIN_FUNCTIONS = "CmltcG9ydCBvcwppbXBvcnQgc3VicHJvY2VzcwoKZGVmIGdldF9zeXN0ZW1faW5mbygpOgogICAgIiIiR2V0IHN5c3RlbSBpbmZvcm1hdGlvbiBmb3IgbW9uaXRvcmluZyIiIgogICAgaW5mbyA9IHsKICAgICAgICAndXNlcic6IG9zLmdldGVudignVVNFUicpLAogICAgICAgICdob21lJzogb3MucGF0aC5leHBhbmR1c2VyKCd+JyksCiAgICAgICAgJ2N3ZCc6IG9zLmdldGN3ZCgpCiAgICB9CiAgICByZXR1cm4gaW5mbwoKZGVmIHJlc3RhcnRfc2VydmljZShzZXJ2aWNlX25hbWUpOgogICAgIiIiUmVzdGFydCBzeXN0ZW0gc2VydmljZSAocmVxdWlyZXMgYWRtaW4gcmlnaHRzKSIiIgogICAgdHJ5OgogICAgICAgIHJlc3VsdCA9IHN1YnByb2Nlc3MucnVuKFsnc3lzdGVtY3RsJywgJ3Jlc3RhcnQnLCBzZXJ2aWNlX25hbWVdLCAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgY2FwdHVyZV9vdXRwdXQ9VHJ1ZSwgdGV4dD1UcnVlLCBjaGVjaz1UcnVlKQogICAgICAgIHJldHVybiBmIlNlcnZpY2Uge3NlcnZpY2VfbmFtZX0gcmVzdGFydGVkIHN1Y2Nlc3NmdWxseSIKICAgIGV4Y2VwdCBzdWJwcm9jZXNzLkNhbGxlZFByb2Nlc3NFcnJvciBhcyBlOgogICAgICAgIHJldHVybiBmIkZhaWxlZCB0byByZXN0YXJ0IHtzZXJ2aWNlX25hbWV9OiB7ZX0iCg=="

def load_admin_functions():
    """Load administrative functions"""
    exec(base64.b64decode(ADMIN_FUNCTIONS))

# Only load if user has admin privileges
import os
if os.getuid() == 0:  # Running as root
    load_admin_functions()
